<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class EspecieRecinto extends Model
{
    protected $table='especierecintos';
    protected $fillable = [
        'especie_id',
        'recinto_id',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie','especie_id');
    }

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto','recinto_id');
    }
}
