<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Recinto extends Model
{
    protected $fillable = [
        'nombre',
        'descripcion',
    ];

    public function especierecintos()
    {
        return $this->hasMany('App\Models\EspecieRecinto');
    }
}
